# Generated by Django 3.2 on 2021-05-03 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_ordermodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='ordermodel',
            name='is_shipped',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.IntegerField(choices=[('is_paid', 'is_paid'), ('is_shipped', 'is_shipped')], default=None),
        ),
    ]
