# Generated by Django 3.2 on 2021-05-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20210503_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.IntegerField(blank=True, choices=[('is_paid', 'is_paid'), ('is_shipped', 'is_shipped')], null=True),
        ),
    ]
